### ISSUE TITLE
Crash When Using Woodcutter From Charm

### ISSUE THREAD

**Issue by DistantDig** [pitbox46/ItemBlacklist#11]
I loaded up a pack with just Charm and Item Banning on Fabric 1.19.2, and i get a crash whenever I try to pull an item from its inventory. In my case, i put oak planks in the woodcutter, and the crash always happens right when i try to take it back out. This crash doesnt happen with just charm loaded.

Crash Report:
https://pastebin.com/Yx9ttkX6

**Comment by pitbox46** [comment]
I am _not_ affiliated with the Fabric version of the mod. Only the Forge version. Please talk to the Fabric version's developer
